language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install -r requirements.txt -r requirements-dev.txt
  - pip install Django$DJANGO_VERSION
env:
    - DJANGO_VERSION=">=1.11"
    - DJANGO_VERSION="<1.11"
    - DJANGO_VERSION="<1.9"
script:
  - python setup.py style
  - python setup.py check
  - python setup.py test
